  config:
    target: "ws://10.10.10.25:10025/websocket"
    phases:
      - duration: 20
        arrivalRate: 10000
  scenarios:
    - engine: "ws"
      flow:
        - loop:
          - send:
              x: 1
              y: 2
          - think: 1

