  config:
    target: "ws://dev.webitel.com/ws/websocket"
    phases:
      - duration: 20
        arrivalRate: 10000
  scenarios:
    - engine: "ws"
      flow:
        - loop:
          - send:
              x: 1
              y: 2
          - think: 1

