  config:
    target: "ws://10.10.10.25:10025/websocket"
    phases:
      - duration: 1
        arrivalRate: 1
  scenarios:
    - engine: "ws"
      flow:
        - loop:
          - send:
              x: 5
              y: 6
          - think: 5

